image: python:3.6

stages:
    - format

before_script:
    - python -V  # Print out python version for debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -e .[testing]

black:
    stage: format
    script:
        - source venv/bin/activate
        - black --check .

docs:
    stage: format
    script:
        - source venv/bin/activate
        - sphinx-build -b html docs builddir && tar -zcf docs_build.tgz builddir
    artifacts:
        paths:
            - docs_build.tgz
        expire_in: 1 week
    only:
        - master
